#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
cp -fr $OPENSHIFT_REPO_DIR/diy/static $OPENSHIFT_DATA_DIR/
rm -fr $OPENSHIFT_REPO_DIR/diy/static

cp -fr $OPENSHIFT_REPO_DIR/diy/template $OPENSHIFT_DATA_DIR/
rm -fr $OPENSHIFT_REPO_DIR/diy/template
