application: YOUR_APP_ID
version: 1
runtime: go
api_version: go1

inbound_services:
- warmup

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /static
  static_dir: static

- url: /clear/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
